wget content.competitivecyclist.com/images/items/large/CHR/CHRA01A/BLU.jpg -O chromag-fu40-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC000Q/STE.jpg -O deity-components-bf800-brendog-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC000Q/STE.jpg -O deity-components-bf800-brendog-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC000Q/STE.jpg -O deity-components-bf800-brendog-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0018/BLU.jpg -O deity-components-os-35-highside-80mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0018/BLU.jpg -O deity-components-os-35-highside-80mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0018/BLU.jpg -O deity-components-os-35-highside-80mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0018/BLU.jpg -O deity-components-os-35-highside-80mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0018/BLU.jpg -O deity-components-os-35-highside-80mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0018/BLU.jpg -O deity-components-os-35-highside-80mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF005J/BL.jpg -O race-face-sixc-35-20mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF005J/BL.jpg -O race-face-sixc-35-20mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002C/GD.jpg -O renthal-fatbar-35-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002C/GD.jpg -O renthal-fatbar-35-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002G/GD.jpg -O renthal-fatbar-lite.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002G/GD.jpg -O renthal-fatbar-lite.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002G/GD.jpg -O renthal-fatbar-lite.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002G/GD.jpg -O renthal-fatbar-lite.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0017/BLU.jpg -O deity-components-os-35-highside-50mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0017/BLU.jpg -O deity-components-os-35-highside-50mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0017/BLU.jpg -O deity-components-os-35-highside-50mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0017/BLU.jpg -O deity-components-os-35-highside-50mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0017/BLU.jpg -O deity-components-os-35-highside-50mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/DTC/DTC0017/BLU.jpg -O deity-components-os-35-highside-50mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002A/UNICB.jpg -O renthal-fatbar-carbon-35-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002D/GD.jpg -O renthal-fatbar-lite-35-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002D/GD.jpg -O renthal-fatbar-lite-35-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002D/GD.jpg -O renthal-fatbar-lite-35-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002B/UNICB.jpg -O renthal-fatbar-lite-carbon-35-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF000F/BK.jpg -O race-face-next-riser-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF000F/BK.jpg -O race-face-next-riser-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF000F/BK.jpg -O race-face-next-riser-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002F/GD.jpg -O renthal-fatbar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002F/GD.jpg -O renthal-fatbar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002F/GD.jpg -O renthal-fatbar.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF008H/BK.jpg -O race-face-atlas-35-35mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF008H/BK.jpg -O race-face-atlas-35-35mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF008H/BK.jpg -O race-face-atlas-35-35mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF008H/BK.jpg -O race-face-atlas-35-35mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF008H/BK.jpg -O race-face-atlas-35-35mm-rise-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/ENV/ENV005X/S35MMCLA.jpg -O enve-m7-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/ENV/ENV005X/S35MMCLA.jpg -O enve-m7-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN0022/S10MMRIS.jpg -O renthal-fatbar-lite-carbon.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN0022/S10MMRIS.jpg -O renthal-fatbar-lite-carbon.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN0022/S10MMRIS.jpg -O renthal-fatbar-lite-carbon.jpg
wget content.competitivecyclist.com/images/items/large/PNW/PNW001H/CEMGRE.jpg -O pnw-components-range-v3-35-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/PNW/PNW001H/CEMGRE.jpg -O pnw-components-range-v3-35-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/PNW/PNW001H/CEMGRE.jpg -O pnw-components-range-v3-35-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002K/BK.jpg -O renthal-fatbar-carbon.jpg
wget content.competitivecyclist.com/images/items/large/REN/REN002K/BK.jpg -O renthal-fatbar-carbon.jpg
wget content.competitivecyclist.com/images/items/large/RCF/RCF000E/BK.jpg -O race-face-next-3-4in-riser-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/ENV/ENV005V/S75MMRIS.jpg -O enve-m6-handlebar.jpg
wget content.competitivecyclist.com/images/items/large/OUC/OUC0011/BLA.jpg -O oneup-components-carbon-handlebar.jpg
